// Auto-generated by @fluixi/start — do not edit.
declare module 'virtual:fluixi-server-fns' {
  export function isServerFnRequest(request: Request): boolean;
  export function handleServerFn(request: Request): Promise<Response>;
}
declare module 'virtual:fluixi-api' {
  export function isApiRequest(request: Request): boolean;
  export function handleApiRequest(request: Request): Promise<Response>;
}
declare module 'virtual:fluixi-i18n' {
  export const messages: Record<string, Record<string, unknown>>;
  export const locales: string[];
  export const defaultLocale: string;
}
