// Auto-generated by @fluixi/core fluixiRoutesPlugin — do not edit manually
declare module 'virtual:fluixi-routes' {
  import type { RouteDefinition } from '@fluixi/core/router-next';
  export const routes: RouteDefinition[];
}
